# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(to='chat.Participant'),
        ),
    ]
